file = open("exception_test.py",encoding="utf-8")
text = file.read()
print(text)
file.close()